#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/silversearcher-ag-el

FLAVOR=$1
PACKAGE=silversearcher-ag-el

case $FLAVOR in
    emacs|*xemacs*|emacs23|emacs22|emacs21|emacs20|emacs19|mule2)
    exit 0
    ;;
esac

if [ ${FLAVOR} != emacs ]; then
    if test -x /usr/sbin/install-info-altdir; then
        echo remove/${PACKAGE}: removing Info links for ${FLAVOR}
        install-info-altdir --quiet --remove --dirname=${FLAVOR} /usr/share/info/silversearcher-ag-el.info.gz
    fi

    echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}
    rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
